import PDFDocument from "pdfkit";
import type { AnalysisRow } from "@/lib/analysis-store";
import { displayNameForPersona, PERSONA_IDS } from "@/lib/personas";

/** M13 · Server-side branded PDF (keeps size well under 5MB for typical runs). */
export function buildAnalysisPdfBuffer(analysis: AnalysisRow): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      margin: 48,
      size: "LETTER",
      info: { Title: `Contrario — ${analysis.title}` },
    });
    const chunks: Buffer[] = [];
    doc.on("data", (c: Buffer) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc
      .fontSize(22)
      .fillColor("#14120f")
      .text("Contrario", { align: "center" });
    doc
      .moveDown(0.3)
      .fontSize(10)
      .fillColor("#5c5346")
      .text("Three investors. One deck. Zero consensus.", { align: "center" });
    doc.moveDown(1.2);
    doc.fontSize(14).fillColor("#14120f").text(analysis.title, { align: "left" });
    doc
      .fontSize(9)
      .fillColor("#6b6254")
      .text(
        `Saved ${new Date(analysis.created_at).toLocaleString()} · source: ${analysis.source}` +
          (analysis.avg_score != null ? ` · avg ${analysis.avg_score}/10` : ""),
        { align: "left" }
      );
    doc.moveDown(1);

    if (analysis.input_preview) {
      doc.fontSize(11).fillColor("#14120f").text("Pitch excerpt", { underline: true });
      doc.moveDown(0.3);
      doc
        .fontSize(9)
        .fillColor("#3d382f")
        .text(analysis.input_preview.slice(0, 3500), { align: "left" });
      doc.moveDown(1);
    }

    for (const id of PERSONA_IDS) {
      const body = (analysis.persona_outputs[id] ?? "").slice(0, 12000);
      doc.addPage();
      doc.fontSize(12).fillColor("#14120f").text(displayNameForPersona(id), {
        underline: true,
      });
      doc.moveDown(0.4);
      doc.fontSize(8.5).fillColor("#2a2620").text(body || "(empty)", {
        align: "left",
      });
    }

    if (analysis.synthesis) {
      doc.addPage();
      doc.fontSize(12).fillColor("#14120f").text("Conflict map", { underline: true });
      doc.moveDown(0.4);
      const cm = analysis.synthesis.conflictMap;
      doc.fontSize(9).fillColor("#3d382f").text("Strengths (green):", { continued: false });
      cm.green.forEach((x) => doc.fontSize(8.5).text(`• ${x}`));
      doc.moveDown(0.5);
      doc.fontSize(9).text("Risks (red):");
      cm.red.forEach((x) => doc.fontSize(8.5).text(`• ${x}`));
      doc.moveDown(0.5);
      doc.fontSize(9).text("Mixed (yellow):");
      cm.yellow.forEach((x) => doc.fontSize(8.5).text(`• ${x}`));
      doc.moveDown(0.8);
      doc.fontSize(12).text("Consensus red flags", { underline: true });
      doc.moveDown(0.4);
      analysis.synthesis.redFlags.forEach((r) => {
        doc.fontSize(9).text(`• ${r.issue}`);
        doc.fontSize(8).fillColor("#5c5346").text(`  Fix: ${r.fix}`);
        doc.fillColor("#3d382f");
      });
    }

    doc
      .fontSize(7)
      .fillColor("#9a9084")
      .text("Generated by Contrario — contrario.app", 48, doc.page.height - 40, {
        align: "center",
        width: doc.page.width - 96,
      });

    doc.end();
  });
}
